services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rickcloudy_db
      MYSQL_USER: app
      MYSQL_PASSWORD: M4k1n5u54h!
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rickcloudy-app

networks:
  rickcloudy-app:
    driver: bridge
    name: rickcloudy-app

volumes:
  mysql_data:
